# Generated by Django 5.0.3 on 2024-05-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.CharField(max_length=2000),
        ),
    ]
