# Generated by Django 5.0.6 on 2024-05-24 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_review_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='users',
            field=models.ManyToManyField(related_name='shop_clusters', to=settings.AUTH_USER_MODEL),
        ),
    ]
